### ISSUE TITLE
[Q] Proper setup / `Cannot use import statement outside a module`

### ISSUE THREAD

**Issue by sculpt0r** [avajs/typescript#43]
Please provide details about:

* What you're trying to do
* What happened
* What you expected to happen

Please share relevant sample code. Or better yet, provide a link to a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

We'll also need your AVA configuration (in `package.json` or `ava.config.*` configuration files) and how you're invoking AVA. Share the installed AVA version (get it by running `npx ava --version`) and `@ava/babel` version (from your `package.json` file).

I try to setup AVA 4 with TS for a bigger project. But to simplify things I reduce the problem to a simply project: https://github.com/sculpt0r/AVAwithTS

Now I try to run `npm run test`. The results is:
![image](https://user-images.githubusercontent.com/6498567/172710973-63d4c70a-691d-4fba-9815-39b05238755c.png)

I tried to follow the documentation of AVA & this plugin:
- installed `AVA` (`4.3.0`)
- installed `@ava/typescript` (`3.0.1`)
- also I found that it should be useful to additionally install `source-map-support` - so I did it and in [cfg file](https://github.com/sculpt0r/AVAwithTS/blob/master/ava.config.cjs) I added:
```json
"require": ['source-map-support/register']
```
- in `.tsconfig` the `outDir` is set to the same directory (`build`) as in AVA config rewrite paths
- also the `compile` is set to `tsc`, but if I try to run tests with `compile` set on `false` and the `build` directory already contains js files - I receive the same results as in the screenshot above

I assume I'm missing something - but I'm not sure what? Is it possible to take a look at the sample project: https://github.com/sculpt0r/AVAwithTS, then run `npm i` and then `npm run test`.

**Comment by novemberborn** [comment]
> * I found that it should be useful to additionally install `source-map-support` - so I did it

AVA enables the source map support built into Node.js so this shouldn't be necessary.

> * also the `compile` is set to `tsc`, but if I try to run tests with `compile` set on `false` and the `build` directory already contains js files - I receive the same results as in the screenshot above

Yea, when set to `tsc` AVA first does a build, and then runs the tests.

---

The generated JS code uses ESM syntax:

```
import test from 'ava';
test('some name', t => {
    t.pass();
});
function someTsSyntax() {
    console.log('anything');
}
//# sourceMappingURL=test.js.map
```

However this is a `test.js` file, and there is no `"type": "module"` in your `package.json`, which means that AVA will `require()` it. The file is treated as CommonJS and you cannot use ESM syntax then.

You need to configure TypeScript to output to the CommonJS module syntax, or switch to ESM properly.

**Comment by sculpt0r** [comment]
Thank you for your explanation ❤️ I'll try to make a proper setup :)

**Comment by sculpt0r** [comment]
Thank you again:
- I was able to run tests by setting `"type": "module"` in `package.json`
- I was able to run test without changing package.json - but just setting `"module": "CommonJS"` in `tsconfig.json`

Also, I removed the `source-map-support`

Time to move to bigger project 🤞

**Comment by sculpt0r** [comment]
Looks like precompiling tests help a lot with time out and speed of tests. Can't confirm 100% - but the only thing that stops me is https://github.com/microsoft/TypeScript/issues/26722#issuecomment-516935532

Overall - it feels like this issue could be closed?

Edit:
100% - precompiled tests works like a charm 👍

**Comment by liby** [comment]
Can you help me look at my configuration here? It looks like something went wrong. 🙏 cc @novemberborn

**Comment by sculpt0r** [comment]
@liby It is hard to look at your config if you do not share it ;)

**Comment by liby** [comment]
> It is hard to look at your config if you do not share it ;)

Oh, sorry, I forgot to attach the [link](https://github.com/liby/hexo-util-rs/blob/feature/test-ava-times-out/package.json#:~:text=%22-,ava,-%22%3A%20%7B)

**Comment by sculpt0r** [comment]
You use old AVA version - is there any reason why you can't upgrade?
Also, you use cfg for the old way of supporting TS. Anyway, we need you to be more informative ;)

What is wrong with your config? Are there any errors? What steps did you try already?

**Comment by liby** [comment]
> You use old AVA version - is there any reason why you can't upgrade?

I am using the [latest version@4.3.3](https://github.com/liby/hexo-util-rs/blob/feature/test-ava-times-out/package.json#L72), are you reading it wrong?

> Anyway, we need you to be more informative ;)

I got the `Timed out while running tests` error in CI/CD. By searching, I found two solutions:
  - [using ts-node/register/transpile-only rather than ts-node/register](https://github.com/avajs/ava/discussions/3033#discussioncomment-2845448)
    - [It doesn't work.](https://github.com/avajs/ava/discussions/3033#discussioncomment-3502747)
  - [Would be interesting to try with `compile: false` and precompile](https://github.com/avajs/ava/discussions/3036#:~:text=Would%20be%20interesting%20to%20try%20with%20compile%3A%20false%20and%20precompile)
  	- That's exactly why I found this place

> What is wrong with your config? Are there any errors? What steps did you try already?

To fix the `Timed out while running tests` error, I made the [following changes](https://github.com/liby/hexo-util-rs/compare/main...feature/test-ava-times-out):
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/38807139/187892410-d2e696ea-6ed5-44cc-8b1f-dd31b77f6db5.png">

But CI/CD started complaining even before the `Timed out while running tests` error appeared:
```
  ✖ Unexpected duplicate extensions in options: ’ts’.
Error: Process completed with exit code 1.
```
So I wonder if I've written my configuration wrong.

**Comment by ddanielcruzz** [comment]
@liby I think you got your config wrong, from the link you shared I see that you have 
```json
"typescript": {
      "rewritePaths": {
        "src/": "build/"
      },
      "compile": false
}
```

But your file structure does not match your `rewritePaths`. Imagine you have your tests at root directory under `tests` and your TypeScript `outDir` is set to `dist`. This would mean that your transpiled tests would be at `dist/tests`


```sh
your-app/
├─ dist/
│  ├─ tests/
│  │  ├─ myTest.js
├─ tests/
│  ├─ myTest.ts
├─ package.json
```

Then your rewrites would have to be 
```json
"typescript": {
      "rewritePaths": {
        "tests/": "dist/tests"
      },
      "compile": "tsc"
}
```

Note that is required that the value of `compile` is set to `tsc`

Looking at your repo you have your tests under `__test__`, since tsc artifacts are not tracked on Git I don't know the name of your `outDir`, your configuration would have to be something like 
```json
"typescript": {
      "rewritePaths": {
        "__test__":  <your-outDir-path-to-tests>
      },
      "compile": "tsc"
}
```

**Comment by liby** [comment]
> Note that is required that the value of `compile` is set to `tsc`

Is this something that has to be done? I disabled it because @novemberborn mentioned that it said “[Would be interesting to try with compile: false and precompile](https://github.com/avajs/ava/discussions/3036#:~:text=Would%20be%20interesting%20to%20try%20with%20compile%3A%20false%20and%20precompile.)” and wanted to try it out.


[After testing](https://github.com/liby/hexo-util-rs/runs/8149913816?check_suite_focus=true), I feel that `tsc` is not suitable for use in my repo.

**Comment by novemberborn** [comment]
With it set to false you need to run tsc yourself before running tests.

**Comment by liby** [comment]
> With it set to false you need to run tsc yourself before running tests.

Thanks for the reminder. So when I get an `Timed out while running tests` error in CI/CD, is setting `compile` to `false` the only solution? [Setting timeout to 80s can solve this issue temporarily, but it will lead to too long job time](https://github.com/avajs/ava/issues/3098#:~:text=will%20lead%20to-,too%20long%20job%20time.,-Write).

**Comment by novemberborn** [comment]
Typically from what I've seen, compilation through loader extensions can take so long, or fails quietly, that AVA gives up. I always precompile so that the tests are run with JavaScript.

Looking at the code, the time taken by `compile: 'tsc'` also counts towards AVAs timeout threshold.

**Comment by liby** [comment]
> I always precompile so that the tests are run with JavaScript.

Because I've been using [`@swc-node/register`](https://github.com/swc-project/swc-node/tree/master/packages/register#ava) to compile.

I also tried to switch to using `tsc` before, but I encountered a lot of issues not knowing how to solve them, can you show me your config?

**Comment by novemberborn** [comment]
https://github.com/avajs/get-port/blob/main/ava.config.js

**Comment by liby** [comment]
> [https://github.com/avajs/get-port/blob/main/ava.config.js](https://github.com/avajs/get-port/blob/main/ava.config.js?rgh-link-date=2022-09-04T14%3A35%3A48Z)

After looking at it, I think there is still a difference between [my repo](https://github.com/liby/hexo-util-rs) and `get-port`. My repo works mainly in the `node` environment. If migrate to `tsc` and use precompile, I will have to change a lot of config like `tsconfig`.

There may be some other problems in this process, so I may continue to use `[@swc-node/register](https://github.com/swc-project/swc-node/tree/master/packages/register?rgh-link-date=2022-09-04T14%3A12%3A01Z#ava)`.
